Draft: Add fetch-file for image preview, download-file function and file setting modal
lern-fair-file-sharing/app pull request #24
Opened 2024-06-17 14:44 UTC by theopfr

Closes #18 
Closes #23

The goal of this MR is:
- [x] fix image preview on file cards
- [ ] add a modal popup to the file cards
- [x] add file-download to file settings modal
- [ ] add file-deletion to file settings modal

I added two util funtions: ``fetchFile`` and ``downloadFile``. I already started to integrate them into the ``FileCard`` component so now you can see image previews on them. Also, on each card there are these three dots on which the user should be able to download/delete the file.
Currently, clicking on the three dots just simply downloads the file. Due to my phone being weird I cannot 100% test if the download works (my file app just isnt loading, dont know why).

So please check if the download works for you. Maybe also someone should check on iOS.

Depends on MR #22 
This MR depends on another which will add the util function for deleting files.

2024-06-17 15:02 UTC, cma5 commented
It seems to download the file i selected. The only problem is, that it doesn't put it on the phones drive.
![Unbenannt](https://github.com/lern-fair-file-sharing/app/assets/68401216/5637056a-0fd4-44c2-8112-ba740cfb3ab5)

2024-06-17 15:05 UTC, cma5 commented
You also have to make a new folder in the dialog in order to set a saving location. But as I said before, the file isn't actually saved there

![grafik](https://github.com/lern-fair-file-sharing/app/assets/68401216/d10d713e-1be9-4540-826e-8d41a25192c9)

2024-06-17 15:13 UTC, cma5 commented
And on IOs like you said it doesn't work anyway.

2024-06-18 07:49 UTC, cma5 commented
![grafik](https://github.com/lern-fair-file-sharing/app/assets/68401216/fb7da67d-1bf5-498a-afb0-ef6c3767c89c)
![2601E1E1-D47B-4C6E-98A4-484834C395FB](https://github.com/lern-fair-file-sharing/app/assets/68401216/6950195b-70ef-4b08-acf8-f06b24c16651)
Functionality wise everything is great, the only thing I would change ist to remove the popup on IOs since when you move out of the share dialog without saving, the file has been saved doesn't make sense.

2024-06-18 07:52 UTC, cma5 requested changes

2024-06-18 07:52 UTC, cma5 commented on app/utils/ServerRequests.tsx
> +        Alert.alert("File Downloaded", `File has been downloaded.`);
please put this only into the android thingie

2024-06-18 15:47 UTC, theopfr commented on app/utils/ServerRequests.tsx
> +        Alert.alert("File Downloaded", `File has been downloaded.`);
The alert text? Can't iOS phones get alerts? I replaced the download ocnfirmation with a toast anyways, but for failures there still is an Alert

2024-06-18 16:29 UTC, cma5 approved these changes
LGTM 👍

2024-06-18 16:56 UTC, merged